### ISSUE TITLE
[Feature]: Publish to Conda

### ISSUE THREAD

**Issue by AHReccese** [openscilab/pymilo#100]
### Describe the feature you want to add

add associated GitHub action to publish to conda(like PyPI auto-upload)

**Comment by AHReccese** [comment]
Hi Sadra, could you please do this task?
@sadrasabouri

**Comment by AHReccese** [comment]
I will soon add the anaconda token to the repositories secrets.

**Comment by AHReccese** [comment]
I will soon add the anaconda token to the repositories secrets.

**Comment by sadrasabouri** [comment]
> Hi Sadra, could you please do this task? @sadrasabouri

Yes, sure. I self-assign it.

> I will soon add the anaconda token to the repositories secrets.

Let me know when you added it then I will start.

**Comment by AHReccese** [comment]
@sepandhaghighi can you start to work on this? it is crucial for this release.

**Comment by sadrasabouri** [comment]
I was waiting for you to add an anaconda token to the repository secret and update this thread. As mentioned in the latest message.

**Comment by AHReccese** [comment]
Oh shit, sorry Sadra, sure!

**Comment by AHReccese** [comment]
@sadrasabouri 
Anaconda Token is added as a single repository secret.
Go ahead man.
