### ISSUE TITLE
What is the difference of this and ONNX?

### ISSUE THREAD

**Issue by ogencoglu** [openscilab/pymilo#36]
#### Description

We can already convert sklearn models to onnx, even add extra metadata if we want, investigate the model intrinsics via https://netron.app/ (locally or on the browser). How is the functionality of pymilo different than ONNX?

**Comment by AHReccese** [comment]
Hi there, I hope you're doing great, here is a comprehensive answer:

ONNX is an open format that is built to represent machine learning models. ONNX defines a set of the building blocks of machine learning models. So, the models exported by ONNX are not exactly the same as the original model. In fact, before exporting, the models are reconstructed (approximately) by the building blocks provided by ONNX.

![image](https://github.com/openscilab/pymilo/assets/32750909/b139e6f4-b89f-436f-94d4-6836fb4708cd)

**Comment by ogencoglu** [comment]
Thank you for the reply!
